name: Copy website source to S3

on:
  push:
    branches:
      - main
<<<<<<< HEAD
    paths:
      - 'src/**'
=======
>>>>>>> a335007dfe9d20b015546faa460a409ad95213a8

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

<<<<<<< HEAD
    - name: Set environment for branch
      run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
              echo "TF_WORKSPACE=prod" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == 'refs/heads/development' || $GITHUB_REF == *'refs/pull'* ]]; then
              echo "TF_WORKSPACE=dev" >> $GITHUB_ENV
          fi
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        # terraform_version: 0.13.0:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
    - name: Terraform Init
      id: init
      run: terraform init -input=false

=======
>>>>>>> a335007dfe9d20b015546faa460a409ad95213a8
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

<<<<<<< HEAD
    - name: Copy files to the website with the AWS CLI and invalidates cache
      run: |
        aws s3 sync src/ s3://$(terraform output website_bucket) --exclude '*.git*' --exclude '*README*'
        aws cloudfront create-invalidation --distribution-id $(terraform output cloudfront_id) --paths "/"
=======
    - name: Copy files to the website with the AWS CLI
      run: |
        source s3_bucket.sh
        aws s3 sync src/ s3://$S3_BUCKET --exclude '*.git*' --exclude '*README*'
>>>>>>> a335007dfe9d20b015546faa460a409ad95213a8
